--1.ÖRNEK:2022 yýlý ocak ayýnda verilen siparýþleri detaylý þekilde ve tarihe göre sýralý þekilde getiriniz
SELECT O.ID,O.DATE_,OD.AMOUNT,OD.UNITPRICE,OD.LINETOTAL,
I.ITEMCODE,I.CATEGORY1,I.CATEGORY2,I.CATEGORY3,I.BRAND
FROM ORDERS O 
JOIN ORDERDETAILS OD 
ON OD.ORDERID=O.ID
JOIN ITEMS I
ON I.ID=OD.ITEMID
WHERE DATE_ BETWEEN '20220101' AND '20220131 23:59:59'
ORDER BY DATE_ DESC

-- BU SORGUDA GÖRÜLDÜÐÜ GÝBÝ YUKARIDA YAPILAN SORGUDA 31 ALINMIYOR.BUNU BÖYLE GÖREBÝLÝYORUZ;
--SELECT CONVERT(DATETIME,'20220131')
--CÖZÜMÜ YUKARIDA TARÝH YERÝNE SAATÝ DE YAZABÝLÝRÝSN 
--VEYA WHERE SARTINA CONVERT(DATE,DATE_) YAZABÝLÝRSÝN

--2.ÖRNEK:nazmiye ercan isimli kullanýcýnýn verdiði siparýþ detayýný getiriniz
SELECT u.NAMESURNAME,O.ID,O.DATE_,I.ITEMCODE,I.ITEMNAME,OD.AMOUNT,OD.UNITPRICE
FROM ORDERS O
JOIN USERS U ON U.ID=O.USERID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ITEMS I ON I.ID=OD.ITEMID
WHERE U.NAMESURNAME='Nazmiye Ercan'


SELECT * FROM ITEMS



--ÖRNEK 3:HER ÞEHRÝN ÝLÇELERÝNÝ GETÝREN SORGU
SELECT T.TOWN,C.CITY FROM TOWNS T
JOIN CITIES C ON C.ID=T.CITYID
ORDER BY C.CITY ,T.TOWN


--ÖRNEK 4:ÝSTANBULDA HANGÝ ÝLÇEDE NE KADAR MÜSTERÝ OLDUÐUNU GETÝREN SORGU
SELECT C.CITY SEHIR,T.TOWN ILCE,COUNT(DISTINCT U.ID) MUSTERISAYISI
FROM ADDRESS A
JOIN USERS U ON U.ID=A.USERID
JOIN CITIES C ON C.ID=A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID
WHERE C.CITY='ÝSTANBUL'
GROUP BY C.CITY,T.TOWN

--ORNEK 5:2022 yýlý mart ayýnda 20-30 yaþ arasý müsterilerin verdiði siparýþleri listeleyiniz
SELECT u.NAMESURNAME,DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) YAS,C.CITY SEHIR,O.DATE_ TARIH,O.ID SIPARISNO,O.TOTALPRICE TOPLAMTUTAR
FROM USERS U
JOIN ORDERS O ON O.USERID=U.ID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID
WHERE DATEDIFF(YEAR,U.BIRTHDATE,GETDATE()) BETWEEN 20 AND 30 --yaþ hesabý
AND O.DATE_ BETWEEN '20220301' AND '20220331 23:59:59'
ORDER BY DATE_

--ÖRNEK6:KULLANICILARIN HANGÝ ÞEHÝRDE KAÇ ADRESÝ OLDUÐUNU BÝLGÝSÝNÝ GETÝRMEK
SELECT U.ID KULLANICIID,U.NAMESURNAME KULLANICI,C.CITY SEHIR,COUNT(A.ID) ADRESSAYISI
FROM USERS U
JOIN ADDRESS A ON A.USERID=U.ID
JOIN CITIES C ON C.ID=A.CITYID
GROUP BY U.ID,U.NAMESURNAME,C.CITY
ORDER BY U.NAMESURNAME

--ORNEK7:ÝSTANBUL'DA YILIN ÝLK 3 AYINDA EN ÇOK SATIÞ YAPILAN 10 ÜRÜNÜ GETÝREN SORGUYU YAZINIZ
SELECT
TOP 10
C.CITY SEHIR,I.ITEMCODE,I.ITEMNAME,I.CATEGORY1,I.CATEGORY2,I.CATEGORY3,
SUM(OD.AMOUNT) TOPLAMADET,SUM(OD.LINETOTAL) TOPLAMTUTAR
FROM ORDERS O
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID
JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
JOIN ITEMS I ON I.ID=OD.ITEMID

WHERE C.CITY='ÝSTANBUL' AND O.DATE_ BETWEEN '20220101' AND '2022-03-31 23:59:59' --20220401
GROUP BY C.CITY ,I.ITEMCODE,I.ITEMNAME,I.CATEGORY1,I.CATEGORY2,I.CATEGORY3
ORDER BY SUM(OD.LINETOTAL) DESC

--ORNEK8:haftanýn günlerine göre ne kadar alýþveriþ yapýldýðý bilgisini getiririz
SELECT 
DATEPART(DW,DATE_),
DATENAME(DW,DATE_),SUM(TOTALPRICE),COUNT(ID) FROM ORDERS
GROUP BY DATENAME(DW,DATE_),DATEPART(DW,DATE_)
ORDER BY DATEPART(DW,DATE_)

--ORNEK9:saat aralýðýna göre ne kadar alýþveriþ yapýldýðý bilgisiniz getiriniz

SELECT DATEPART(HOUR,DATE_) SAAT,
SUM(TOTALPRICE) TOPLAMTUTAR,
COUNT(ID) SIPARISSAYISI
FROM ORDERS
GROUP BY DATEPART(HOUR,DATE_)
ORDER BY 1


--DATEPART(HOUR,'2022-01-01 08:12:12.000'):SAATÝ GETÝRME

--ORNEK10:HER BÝR SÝPARÝÞ ÝÇÝN TOPLAM SEVKETME SÜRESÝNÝ GETÝREN SORGUYU YAZINIZ
SELECT 
O.ID ,U.NAMESURNAME KULLANICI,C.CITY SEHIR,O.DATE_,I.DATE_ FATURATARIHI,DATEDIFF(HOUR,O.DATE_,I.DATE_) SEVKEDILMESURESÝ
FROM ORDERS O
JOIN USERS U ON U.ID=O.USERID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID
JOIN INVOICES I ON I.ORDERID=O.ID
ORDER BY O.ID

--ORNEK11:SÝPARIÞLERRÝN GENEL OLARAK,BÖLGEELRE GÖRE VE SEHÝRLERE GÖRE ORTALAMA SEVKETME SÜRELERÝNÝ GETÝREN SORGU
SELECT AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)*1.0) ORTALAMASEVKEDILMESURESI
FROM ORDERS O
JOIN INVOICES I ON I.ORDERID=O.ID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID

--çýkacak sonuçlarý float olarak istersem AVG(CONVERT(FLOAT(DATEDIFF(HOUR,O.DATE_,I.DATE_))
--CONVERT YAPMADAN:AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)*1.0)
--BÖLGE BAZINDA :
SELECT C.REGION, AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)*1.0) ORTALAMASEVKEDILMESURESI
FROM ORDERS O
JOIN INVOICES I ON I.ORDERID=O.ID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID
GROUP BY C.REGION

--SEHÝR KIRILIMI BAZINDA
SELECT C.REGION, C.CITY , AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)*1.0) ORTALAMASEVKEDILMESURESI
FROM ORDERS O
JOIN INVOICES I ON I.ORDERID=O.ID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID
GROUP BY C.REGION,C.CITY

--ÖRNEK 12:SÝPARÝÞ TARÝHÝNÝN AYI ÝLE FATURA TARÝHÝNÝN AYI FARKLI OLAN SÝPARIÞLERÝ GETÝRÝNÝZ
SELECT O.ID SIPARISNO,O.DATE_ SIPARISTARIHI,I.DATE_ FATURATARIHI,DATENAME(MONTH,O.DATE_) SIPARISSAYI,
DATENAME(MONTH,I.DATE_) FATURAYI
FROM ORDERS O
JOIN INVOICES I ON I.ORDERID=O.ID
WHERE DATENAME(MONTH,O.DATE_)  <> DATENAME(MONTH,I.DATE_) 
ORDER BY 1

--ORNEK13:HER AY ÝÇÝN SÝPARIÞ TARÝHÝNÝN AYI VE FATURA TARÝHÝNÝN AYI FARKLI OLAN SÝPARÝÞ SAYILARI GETÝRÝN
SELECT  DATENAME(MONTH,O.DATE_) SIPARISAYISI,COUNT(DATENAME(MONTH,I.DATE_)) FATURASI_SONRAKI_AY_KESILEN_SIPARIS_SAYISI
FROM ORDERS O
JOIN INVOICES I ON I.ORDERID=O.ID
WHERE DATENAME(MONTH,O.DATE_)<>DATENAME(MONTH,I.DATE_)
GROUP BY DATENAME(MONTH,O.DATE_),DATEPART(MONTH,O.DATE_)
ORDER BY DATEPART(MONTH,O.DATE_)


--ORNEK14:her þehirde ne kadar erkek ne kadar kadýn kullanýcýnýn olduðunu getiren sorgu yazýnýz
SELECT U.GENDER CINSIYET,CT.CITY SEHIR,COUNT(A.ID) KÝSÝSAYÝSÝ
FROM ADDRESS A
JOIN USERS U ON U.ID=A.USERID
JOIN CITIES CT ON CT.ID=A.CITYID
GROUP BY CT.CITY,U.GENDER
ORDER BY 1,2

--ORNEK15:ÜRÜN KATEGORÝLERÝNÝ ALFABETÝK OLARAK ANA KATEGORÝ VE EN ÇOK SATAN OLARAK ALT KATEGORÝ OLACAK ÞEKÝLDE GETÝRÝNÝZ
SELECT I.CATEGORY1 ANAKATEGORÝ,I.CATEGORY2 ALTKATEGORÝ,SUM(OD.LINETOTAL) TOPLAMSATIS
FROM ORDERDETAILS OD
JOIN ITEMS I ON I.ID=OD.ITEMID
GROUP BY I.CATEGORY1,I.CATEGORY2
ORDER BY 1,3 DESC

--ORNEK16:'deterjan temýzlýk' ve 'gýda' kategorilerinde ürünlerin bölgelere göre yapýlan toplam satýþlarý getiriniz
SELECT I.CATEGORY1,SUM(OD.LINETOTAL) SATIS,C.REGION
FROM ORDERDETAILS OD
JOIN ITEMS I ON I.ID=OD.ITEMID
JOIN ORDERS O ON O.ID=OD.ITEMID
JOIN ADDRESS A ON A.ID=O.ADDRESSID
JOIN CITIES C ON C.ID=A.CITYID
WHERE I.CATEGORY1 IN ('DETERJAN TEMÝZLÝK','GIDA')
GROUP  BY  I.CATEGORY1,C.REGION


--ÖRNEK17:her bir ürün için toplam ne kadarlýk satýþ yapýldýðýný adet ve toplam ciro olarak getiriniz.
--ayrýca her bir ürün için en düþük,en yüksek,ortalama satýþ ve mevcut fiyata göre kar-zarar hesabýný yapan sorguyu yazýnýz
SELECT I.ITEMCODE,I.ITEMNAME,I.UNITPRICE BIRIMFIYAT,
SUM(OD.AMOUNT) TOPLAMADET,
ROUND(SUM(OD.LINETOTAL),0) TOPLAMSATIS,
MIN(OD.UNITPRICE) ENDUSUKFIYAT,
MAX(OD.UNITPRICE) ENYUKSEK,
ROUND(AVG(OD.UNITPRICE),2) ORTALAMAFIYAT,
ROUND(SUM(I.UNITPRICE*OD.AMOUNT),0) LISTESATISFIYAT,
ROUND((SUM(OD.LINETOTAL)-SUM(I.UNITPRICE*OD.AMOUNT)),0) KARZARAR,
ROUND(100*(SUM(OD.LINETOTAL)-SUM(I.UNITPRICE*OD.AMOUNT))
/SUM(I.UNITPRICE*OD.AMOUNT),2) KARZARARYUZDE
FROM ORDERDETAILS OD
JOIN ITEMS I ON OD.ITEMID=I.ID
GROUP BY I.ITEMCODE,I.ITEMNAME,I.UNITPRICE
ORDER BY I.ITEMCODE

--ORNEK18:alýþ liste fýyatý ve satýþ fiyatý ile satýlan miktar üzerinden en çok kar edilen 10 ürün ile en az kar edilen 10 ürünü listeleyiniz
SELECT *,TOPLAMSATIS-LISTESATISFIYAT ,
         ROUND(100*( TOPLAMSATIS-LISTESATISFIYAT)/LISTESATISFIYAT,2) KARZARARYUZDE
FROM (
SELECT I.ITEMCODE,I.ITEMNAME,I.UNITPRICE BIRIMFIYAT,
   SUM(OD.AMOUNT) TOPLAMADET,
   ROUND(SUM(OD.LINETOTAL),0) TOPLAMSATIS,
   MIN(OD.UNITPRICE) ENDUSUKFIYAT,
   MAX(OD.UNITPRICE) ENYUKSEK,
   ROUND(AVG(OD.UNITPRICE),2) ORTALAMAFIYAT,
   ROUND(SUM(I.UNITPRICE*OD.AMOUNT),0) LISTESATISFIYAT
FROM ORDERDETAILS OD
JOIN ITEMS I ON OD.ITEMID=I.ID
GROUP BY I.ITEMCODE,I.ITEMNAME,I.UNITPRICE
) T
ORDER BY KARZARARYUZDE DESC

